version: '2'

services:
    nginx:
        volumes:
            - .docker/certs:/etc/letsencrypt
        env_file:
            - ./.docker/local.env

    php:
        env_file:
            - .docker/local.env
        volumes:
            - ./app/code/JH:/var/www/app/code/JH

    db:
        env_file:
            - ./.docker/local.env
        volumes:
            - .docker/db/:/docker-entrypoint-initdb.d/

#    rabbitmq:
#        env_file:
#            - ./.docker/local.env

    mail:
        container_name: m23-mail
        image: mailhog/mailhog
        ports:
            - 1025
            - 8025:8025

    blackfire:
        container_name: m23-blackfire
        image: blackfire/blackfire
        env_file:
            - .docker/local.env
